Repository migtools/velero-plugin-for-vsm, pull requests merged in 2023-02, with the labels that each got.

#4 Add LICENSE
  LICENSE
Labels: lgtm

#5 Add OWNERS
  OWNERS
Labels: do-not-merge/invalid-owners-file, lgtm

#2 OADP-987: Add VSM restore plugins
  go.mod
  go.sum
  internal/restore/volumesnapshot_action.go
  internal/restore/volumesnapshotclass_action.go
  internal/restore/volumesnapshotrestore_action.go
  internal/util/util.go
  internal/util/util_test.go
  main.go
Labels: lgtm, approved

#6 Add .gitignore file
  .gitignore
Labels: lgtm, approved
